# Generated by Django 4.1.5 on 2023-03-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0009_update_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='update_profile',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
